# Stage 1: Build React app
FROM node:14-alpine as build

WORKDIR /app/react-movie

COPY ./react-movie/package.json /app/react-movie/
COPY ./react-movie/package-lock.json /app/react-movie/
COPY ./react-movie/public /app/react-movie/public
COPY ./react-movie/src /app/react-movie/src

RUN npm install
RUN npm run build

# Stage 2: Serve React app using Nginx
FROM nginx:alpine

COPY --from=build /app/react-movie/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
