version: '3'

services:
  app:
    build:
      context: .
      dockerfile: DockerFile.client
    ports:
      - "3000:80"
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: DockerFile.api
    expose:
      - "5000"
